Start work on matrix stack.
badgeteam/ESP32-platform-firmware pull request #213
Opened 2020-07-18 17:46 UTC by robotman2412

Adds the 2D matrix stack to the window object.
Creates a global 2D matrix stack in case of no specified window.
Adds more options to the framebuffer config to configure the matrix stack.

2020-07-18 17:56 UTC, tjclement commented on firmware/components/driver_framebuffer/Kconfig
> +menu "Driver: framebuffer & matrices support"
These matrices are not separate from the framebuffer driver, are they? It is my understanding that they are used to transform render layers ("windows"). I see them more as animation properties on windows than as a separate functionality.

2020-07-18 17:58 UTC, tjclement commented on firmware/components/driver_framebuffer/Kconfig
> +		int "Initial size allocated to the matrix stack"
What is a matrix stack, and what does this size do?

2020-07-18 18:09 UTC, tjclement reviewed
Thanks for the update on your work. I think it's cool to have linear transformations in our graphics layer. I hope that we will be able to do animations with it in the future.

I'm not yet sure whether this exact implementation you're proposing is the way to go, but very curious to see where you're going.

2020-07-18 18:09 UTC, tjclement commented on firmware/components/driver_framebuffer/driver_framebuffer_window.cpp
> +	/* Initialise matrix stack */
I try to comment _why_ I do something rather than _what_ I do, because the what is usually apparent and the why is unclear to others

2020-07-18 18:09 UTC, tjclement commented on firmware/components/driver_framebuffer/Kconfig
> +	config MATRIX_STACK_INITIAL_SIZE
What is a matrix stack, and what does this size do?

2020-07-18 18:09 UTC, tjclement commented on firmware/components/driver_framebuffer/Kconfig
> +menu "Driver: framebuffer & matrices support"
These matrices are not separate from the framebuffer driver, are they? It is my understanding that they are used to transform render layers ("windows"). I see them more as animation properties on windows than as a separate functionality.

2020-07-18 18:09 UTC, tjclement commented on firmware/components/driver_framebuffer/include/driver_framebuffer_compositor.h
> +	/* RobotMan2412's matrix stack */
Would be nice to explain here what the matrices will be used for

2020-07-18 18:51 UTC, robotman2412 commented
To answer many of your questions:

The matrix stack is indeed not a separate system, but i added it to the name to make it easier to find.

Matrices are used to manipulate the canvas, look at it like warping the cloth you draw on.

The matrix stack functions to be able to recover a transformation matrix you may want to use later on, and functions like any other stack.
A stack is last-on-first-off, which makes it so unique and usefull in many fields, in this case you can say: scale the canvas and move it, then push, apply some other arbitrary transformation, then pop and the other arbitrary transformation will not affect it anymore.
This push/pop effect can be nested by the nature of a stack.

To the stack size:
It is bad to let a stack expand itself infinitely, because errored code will just keep going and make it more difficult to find out what happened.
Therefor, i made an intentional limit which can be changed.

For now, the code is far from done.
I will add more comments here as you asked.

2020-07-19 20:51 UTC, renzenicolai commented
Cool stuff, let's see where this goes.

Small initial hints: please change only the minimum needed, please don't change the driver name and please don't put your name in stuff, you're contributing to a work for badge.team, that it's your work will be aparent from the git commit history.

2020-07-22 13:54 UTC, robotman2412 commented
I feel that this is _nearly_ ready to be merged.
The 2D functions are very nearly done, and when fully done i advise to merge this as the features afterwards will take much longer to mature.

2020-07-22 13:56 UTC, robotman2412 commented
Demonstration of the graphics can be found here:
[gist: boats.py](https://gist.github.com/robotman2412/337720ad9866055448bbb7761f507024)

2020-08-02 00:14 UTC, renzenicolai commented
Very, very nice work, however I have some points that I would like to see addressed before I can allow this to be merged:
 - Floating point operations in the basic (2d) drawing functions shouldn't be there
 - You have multiple comments referring to your name like "This file is NOT part of an external library but is rather created and maintained by RobotMan2412 and the badge team." you can probably be assured that no one will touch these files. You can add your name to the top of each file you create if you really want your name to be in there, but please don't "claim" parts of the project: it's a group thing, other people can work on your code, just like you did with "my" framebuffer driver :P
 - Please have all the new functions in a separate file as to not clutter the basic drawing routines file with the new stuff
 - Please make the new functions optional with a menuconfig flag
 - Maybe add different parts of your big new addition as separate PRs, I promise you that we will look at them quickly once we start the merging process, it's just that this PR is very, very big.
 - Please don't add commented out code sections, no matter how "usefull" a commented out line might be to you, if it's commented out then it doesn't work. Comments are for... comments :-)
 - If you see commented out code lines in files that you edit feel free to remove them too as I might have slipped up in the past, this whole thing was thrown together in a hurry

2020-08-02 10:25 UTC, robotman2412 commented
To respond to your questions:

Floating point operations shouldn't be there for simple 2D?
I don't understand this point.
The matrix stack uses floating point numbers, and allowing floats to be input simply removes some clutter and allows programmers more flexibility.
If you think this is really important, please elaborate.

That's right.
I did forget to remove my name from a few comments.
I did that now.

I was thinking about seperating maybe things like shaders into their own files.
It seems you agree, so that can be done.
This does imply that you want me to make a new file with all new functions, and keep the old file untouched.
I can do this, tough i thought the drawing functions fit quite nicely where they are now.

Making new functions optional seperately?
I think this is more trouble than it's worth:
<ul>
<li>The new circle depends on triangles and the matrix stack.</li>
<li>The new quad depends on triangles.</li>
<li>The new text depends on textured triangles.</li>
<li>Textured triangles depend on textures and shaders.</li>
</ul>
I understand your point, but i strongly advise against seperating these features with on/off.

I do agree that this pull request is quite big.
Then again, the amount of things to change to get fancy new graphics is also big.
I don't blame any of you for it, but your drawing functions were very simple, possibly because of not having a graphics guy.
I noticed very early on that some features which many other libraries had were simply missing.
Which is why i add things like the triangle and quad, they're easy enough to implement nd make your life so much easier.

There is indeed a large commented out block, from when i was working on lines.
I simply didn't remove it yet.
I'll also do that.

If you want me to, i can remove other code comments.

2020-08-02 18:58 UTC, robotman2412 commented
I'm satisfied with the current version.
There is some features which i would like to add later, but without further notice this is v1.0.

2020-08-05 11:53 UTC, robotman2412 commented
no wait i broke it

2020-08-05 15:04 UTC, robotman2412 commented
False alarm, i cleaned build and it worked.

2020-08-05 19:00 UTC, renzenicolai requested changes
Close, you're almost there!

I do have some small points though, please check the comments I added.

2020-08-05 19:00 UTC, renzenicolai commented on firmware/components/driver_framebuffer/Kconfig
> +		int "Size allocated to the matrix stack by default"
Size in what? bytes? kilobytes?

2020-08-05 19:00 UTC, renzenicolai commented on firmware/components/driver_framebuffer/driver_framebuffer.cpp
> +	//Initialise the globl matrix stack.
Please remove these comments, might be fun to explain this in the docs, but the code is not the place for this...

2020-08-05 19:00 UTC, renzenicolai commented on firmware/components/driver_framebuffer/driver_framebuffer.cpp
> +	//later on, i may want to add a 3D matrix stack and a depth buffer, required elements for 3D graphics
It's good that you have plans, but again: not here

2020-08-05 19:00 UTC, renzenicolai commented on firmware/components/driver_framebuffer/driver_framebuffer_window.cpp
> +	/* Initialise matrix stack */
I agree, useless comment, but so are most of mine so meh, leave it if you want to :-)

2020-08-05 19:00 UTC, renzenicolai commented on firmware/components/driver_framebuffer/driver_framebuffer_window.cpp
> +	free(window->stack_2d->matrices);
Did you ifdef these?

2020-08-05 19:00 UTC, renzenicolai commented on firmware/components/micropython/esp32/modframebuffer.c
>  /* Get the color of a pixel in the framebuffer or in a window. Arguments: window (optional), x, y */
Please update the description too

2020-08-05 19:00 UTC, renzenicolai commented on firmware/components/micropython/esp32/modframebuffer.c
> +static MP_DEFINE_CONST_FUN_OBJ_VAR_BETWEEN( framebuffer_draw_pixel_obj,           3, 5, framebuffer_draw_pixel);
Please update the description too

2020-08-05 19:00 UTC, renzenicolai commented on firmware/components/driver_framebuffer/driver_framebuffer.cpp
> +	matrix_stack_2d_init(&stack_2d_global);
I sense a missing ifdef? Please make it possible to completely disable the matrix functionality.

2020-08-06 11:31 UTC, renzenicolai approved these changes

2020-08-06 11:32 UTC, merged